trigger:
  branches:
    include:
      - main   # ou master selon ta branche

pool:
  vmImage: 'ubuntu-latest'

variables:
  phpVersion: '8.2'
  symfonyEnv: 'test'

steps:
  # 1. Installer PHP
  - task: UsePHPVersion@0
    inputs:
      version: '$(phpVersion)'
      addToPath: true

  # 2. Installer Composer
  - script: |
      sudo apt-get update
      sudo apt-get install -y unzip curl git
      curl -sS https://getcomposer.org/installer | php
      sudo mv composer.phar /usr/local/bin/composer
    displayName: 'Install Composer'

  # 3. Installer dépendances Symfony
  - script: |
      composer install --no-interaction --no-progress --prefer-dist
    displayName: 'Composer install'

  # 4. Créer la base de données de test
  - script: |
      php bin/console doctrine:database:create --env=$(symfonyEnv)
      php bin/console doctrine:migrations:migrate --no-interaction --env=$(symfonyEnv)
    displayName: 'Prepare test database'

  # 5. Lancer PHPUnit
  - script: |
      php bin/phpunit --testdox
    displayName: 'Run PHPUnit tests'
