version: '3.8'

services:
  php:
    build:
      context: .
    container_name: evenmonet_php
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://symfony:symfony@database:5432/symfony

  database:
    image: postgres:16
    container_name: evenmonet_db
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  jenkins:
    image: jenkins/jenkins:lts
    container_name: evenmonet_jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # 🔑 Donne accès à Docker de l’hôte
      - /usr/bin/docker:/usr/bin/docker           # 🔑 Binaire docker dispo dans Jenkins

volumes:
  db_data:
  jenkins_home:
